# Hello FMOD Backend 应用配置

[server]
host = "0.0.0.0"
port = 3000
workers = 4

[database]
# 数据库连接配置
# 开发环境使用SQLite，生产环境使用PostgreSQL
url = "sqlite:data/app.db"
# url = "postgresql://user:password@localhost:5432/hello_fmod"
max_connections = 10
min_connections = 2
connect_timeout = 30
idle_timeout = 600

[logging]
level = "info"
format = "json"

[cors]
allow_origins = ["http://localhost:3000", "http://127.0.0.1:3000"]
allow_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allow_headers = ["content-type", "authorization"]

[security]
secret_key = "your-secret-key-here"
jwt_expiry = 86400  # 24小时（秒）

[features]
# 功能开关
enable_metrics = true
enable_tracing = true
enable_cors = true 